Update esphomeyaml-edge

diff --git a/docker/Dockerfile.hassio b/docker/Dockerfile.hassio
--- a/docker/Dockerfile.hassio
+++ b/docker/Dockerfile.hassio
@@ -1,40 +1,78 @@
-# Dockerfile for HassIO add-on
-ARG BUILD_FROM=homeassistant/amd64-base-ubuntu:latest
+ARG BUILD_FROM=hassioaddons/ubuntu-base:2.2.0
+# hadolint ignore=DL3006
 FROM ${BUILD_FROM}
 
-RUN apt-get update && apt-get install -y --no-install-recommends \
+# Set shell
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+
+# Copy root filesystem
+COPY esphomeyaml-edge/rootfs /
+COPY setup.py setup.cfg MANIFEST.in /opt/esphomeyaml/
+COPY esphomeyaml /opt/esphomeyaml/esphomeyaml
+
+RUN \
+    # Temporarily move nginx.conf (otherwise dpkg fails)
+    mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bkp \
+    # Install add-on dependencies
+    && apt-get update \
+    && apt-get install -y --no-install-recommends \
+        # Python for esphomeyaml
         python \
         python-pip \
         python-setuptools \
+        # Python Pillow for display component
         python-pil \
+        # Git for esphomelib downloads
         git \
-    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* && \
-    pip install --no-cache-dir --no-binary :all: platformio && \
-    platformio settings set enable_telemetry No && \
-    platformio settings set check_libraries_interval 1000000 && \
-    platformio settings set check_platformio_interval 1000000 && \
-    platformio settings set check_platforms_interval 1000000
-
-COPY docker/platformio.ini /pio/platformio.ini
-RUN platformio run -d /pio; rm -rf /pio
-
-
-COPY . .
-RUN pip install --no-cache-dir --no-binary :all: -e . && \
-    pip install --no-cache-dir --no-binary :all: tzlocal
-
-CMD ["esphomeyaml", "/config/esphomeyaml", "dashboard"]
+        # Ping for dashboard online/offline status
+        iputils-ping \
+        # NGINX proxy
+        nginx \
+    \
+    && mv /etc/nginx/nginx.conf.bkp /etc/nginx/nginx.conf \
+    \
+    && pip2 install --no-cache-dir --no-binary :all: -e /opt/esphomeyaml \
+    \
+    # tzlocal for automatic timezone detection
+    && pip2 install --no-cache-dir --no-binary :all: tzlocal \
+    \
+    # Change some platformio settings
+    && platformio settings set enable_telemetry No \
+    && platformio settings set check_libraries_interval 1000000 \
+    && platformio settings set check_platformio_interval 1000000 \
+    && platformio settings set check_platforms_interval 1000000 \
+    \
+    # Build an empty platformio project to force platformio to install all fw build dependencies
+    # The return-code will be non-zero since there's nothing to build.
+    && (platformio run -d /opt/pio; echo "Done") \
+    \
+    # Cleanup
+    && rm -fr \
+        /tmp/* \
+        /var/{cache,log}/* \
+        /var/lib/apt/lists/* \
+        /opt/pio/
 
 # Build arugments
-ARG ADDON_ARCH
-ARG ADDON_VERSION
+ARG BUILD_ARCH=amd64
+ARG BUILD_DATE
+ARG BUILD_REF
+ARG BUILD_VERSION
 
 # Labels
 LABEL \
     io.hass.name="esphomeyaml" \
-    io.hass.description="esphomeyaml HassIO add-on for intelligently managing all your ESP8266/ESP32 devices." \
-    io.hass.arch="${ADDON_ARCH}" \
+    io.hass.description="Manage and program ESP8266/ESP32 microcontrollers through YAML configuration files" \
+    io.hass.arch="${BUILD_ARCH}" \
     io.hass.type="addon" \
-    io.hass.version="${ADDON_VERSION}" \
-    io.hass.url="https://esphomelib.com/esphomeyaml/index.html" \
-    maintainer="Otto Winter <contact@otto-winter.com>"
+    io.hass.version=${BUILD_VERSION} \
+    maintainer="Otto Winter <contact@otto-winter.com>" \
+    org.label-schema.description="Manage and program ESP8266/ESP32 microcontrollers through YAML configuration files" \
+    org.label-schema.build-date=${BUILD_DATE} \
+    org.label-schema.name="esphomeyaml" \
+    org.label-schema.schema-version="1.0" \
+    org.label-schema.url="https://esphomelib.com" \
+    org.label-schema.usage="https://github.com/OttoWinter/esphomeyaml/tree/dev/esphomeyaml/README.md" \
+    org.label-schema.vcs-ref=${BUILD_REF} \
+    org.label-schema.vcs-url="https://github.com/OttoWinter/esphomeyaml" \
+    org.label-schema.vendor="esphomelib"
